#!/bin/bash
#PBS -l nodes=4:ppn=2:myri
#PBS -l walltime=00:0:50
#PBS -o pfilter.out
#PBS -A lc_jnc
#PBS -j oe
#PBS -N pfilter


source /usr/usc/mpich2/1.3.1..10/setup.sh

WORK_HOME=/home/rcf-40/rshemira/hw2/src

cd $WORK_HOME
np=$(cat $PBS_NODEFILE | wc -l)

filter=mean

# note that we will vary window size when testing
window_size=4
mpirun -np $np -machinefile $PBS_NODEFILE ./pfilter input/moon_in.tiff moon_out.tif $filter $window_size


